### ISSUE TITLE
kradziej

### ISSUE THREAD

**Issue by lisqu16** [ProgramistaZpolski/chrum-95-browser#1]
kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz >:C

**Comment by lisqu16** [comment]
kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz kradniesz

**Comment by ProgramistaZpolski** [comment]
to trzeba było zrobić to przedemną

**Comment by lisqu16** [comment]
a spierdalaj

**Comment by ProgramistaZpolski** [comment]
nein

**Comment by ProgramistaZpolski** [comment]
a i tak przy okazji to jest Chrum-95
ty możesz zrobić sobie własnego chruma

**Comment by lisqu16** [comment]
inwalida

**Comment by ProgramistaZpolski** [comment]
xD
